name: CI & CD
on:
  push:
    branches:
      - main
      - dev
      - "hotfix-**"
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: sudo npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_USER: ${{ secrets.ROOT }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ROOT }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist/"
          TARGET: "/var/www/react/login/"
          EXCLUDE: "/dist/, /node_modules/"
  # CD:
  #   runs-on: ubuntu-latest
  #   needs: CI
  # 不能和 CI任务分开, CI任务构建完成后, 不会保留dist文件, CD任务里找不到dist
  #   steps:
  #     - name: Deploy
  #       uses: easingthemes/ssh-deploy@main
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ROOT }}
  #         ARGS: "-rltgoDzvO"
  #         SOURCE: "dist/"
  #         REMOTE_HOST: ${{ secrets.SERVER_IP }}
  #         REMOTE_USER: ${{ secrets.ROOT }}
  #         TARGET: "/var/www/react/login/"
  #         EXCLUDE: "/dist/, /node_modules/"
